# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2020-11-30 11:36
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaiduContentModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fa_content', models.CharField(default='', max_length=255)),
                ('content', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='MotionModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('positive_rate', models.CharField(max_length=255)),
                ('news_number', models.CharField(max_length=255)),
                ('date_time', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='NeedTitleModel',
            fields=[
                ('key_words', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('add_user', models.CharField(default='', max_length=255)),
                ('create_time', models.DateField(default=datetime.datetime.now)),
                ('has_get_past_news', models.BooleanField(default=False)),
                ('has_send_email', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='NewsListModel',
            fields=[
                ('url', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('key_words', models.CharField(default='', max_length=255)),
                ('author_relative_time', models.CharField(max_length=255)),
                ('time', models.DateField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='NewsModel',
            fields=[
                ('url', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('key_words', models.CharField(default='', max_length=255)),
                ('title_key', models.CharField(default='', max_length=300)),
                ('motion', models.CharField(default='', max_length=250)),
                ('time', models.DateField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='OfflineWord2vecModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key1', models.CharField(max_length=255)),
                ('key2', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SuggestionModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=255)),
                ('suggestion', models.TextField(default='')),
            ],
        ),
    ]
